### ISSUE TITLE
Error while running ID-CGAN

### ISSUE THREAD

**Issue by nebupulickal** [TheLethargicOwl/Single-Image-De-Raining-Keras#2]
I am getting the following error when i try to execute the code

> 
Traceback (most recent call last):
  File "C:\Users\......\anaconda3\envs\AI\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\......\anaconda3\envs\AI\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\.....\.vscode\extensions\ms-python.python-2020.8.108011\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\.....\.vscode\extensions\ms-python.python-2020.8.108011\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\......\.vscode\extensions\ms-python.python-2020.8.108011\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Users\.......\anaconda3\envs\AI\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\.......\anaconda3\envs\AI\lib\runpy.py", line 236, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "d:\Single-Image-De-Raining-Keras-master\ID-CGAN.py", line 323
    img_b = np.array([img_B])/127.5 - 1
          ^
SyntaxError: invalid syntax
>

**Comment by Mahmood-Hussain** [comment]
replace this line with    ` img_show = np.zeros((m,2*n))`

**Comment by Mahmood-Hussain** [comment]
fixed here https://github.com/Mahmood-Hussain/Single-Image-De-Raining-Keras
